dist: bionic

language: node_js
node_js:
  - "lts/*"

addons:
  chrome: stable

before_install:
  - google-chrome-stable --headless --disable-gpu

install: npm test && npm ci

script: npm test

cache: npm
