dist: bionic

language: node_js
node_js:
  - node
  - "lts/*"

before_install:
  - sudo apt-get update
  - npm i -g npm@latest

addons:
  apt:
    sources:
      - google-chrome
    packages:
      -google-chrome-stable

install: npm ci

script: npm test

cache: npm
