dist: bionic

language: node_js
node_js:
  - node
  - "lts/*"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      -google-chrome-stable

before_install: npm i -g npm@latest

install: npm ci

script: npm test

cache: npm
